openapi: 3.1.1
info:
    title: API de exemplo do instagram
    description: uma api de teste
    version: 0.0.1

tags: 
  - usuarios
  - postagens
  - comentarios
  - curtidas


paths:
   /api/usuarios:
     get:
        tag: [usuarios]
        description: buscar todos os usuarios
     post:
   /api/usuarios/id:
     get:
     post:

components:
    schemas:
      Usuario:
        type: object
        properties: 
          id:
            type: interger
            example: 1
          nome:
             type: string
             example: chico cesar
